name: "Make installer action"
on:
  push:
    branches: ["main"]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'auto.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'auto.exe'
          options: --onefile
