name: "Make installer action"
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'auto.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'auto.exe'
          options: --onefile
  release:
    runs-on: windows-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@v2
      with:
        args: "dist/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
